let W_Buttons =[ 
  {
    name : "w-button C0",
    nameText: "A",
    i : 0,
  },
  {
    name : "w-button D0",
    nameText: "S",
    i : 1,
  },
  {
    name : "w-button E0",
    nameText: "D",
    i : 2,
  },
  {
    name : "w-button F0",
    nameText: "F",
    i : 3,
  },
  {
    name : "w-button G0",
    nameText: "G",
    i : 4,
  },
  {
    name : "w-button A0",
    nameText: "H",
    i : 5,
  },
  {
    name : "w-button B0",
    nameText: "J",
    i : 6,
  },
  {
    name : "w-button C1",
    nameText: "K",
    i : 7,
  },
  {
    name : "w-button D1",
    nameText: "L",
    i : 8,
  },
  {
    name : "w-button E1",
    nameText: "1",
    i : 9,
  },
  {
    name : "w-button F1",
    nameText: "2",
    i : 10,
  },
  {
    name : "w-button G1",
    nameText: "3",
    i : 11,
  },
  {
    name : "w-button A1",
    nameText: "4",
    i : 12,
  },
  {
    name : "w-button B1",
    nameText: "5",
    i : 13,
  },
  {
    name : "w-button C2",
    nameText: "6",
    i : 14,
  },
  {
    name : "w-button D2",
    nameText: "7",
    i : 15,
  },
  {
    name : "w-button E2",
    nameText: "8",
    i : 16,
  },
  {
    name : "w-button F2",
    nameText: "9",
    i : 17,
  },
  {
    name : "w-button G2",
    nameText: "0",
    i : 18,
  },
  {
    name : "w-button A2",
    nameText: "/",
    i : 19,
  },
  {
    name : "w-button B2",
    nameText: "*",
    i : 20,
  },
  {
    name : "b-button C#0",
    nameText: "Q",
    i : 21,
    pos : 55,
  },
  {
    name : "b-button D#0",
    nameText: "W",
    i : 22,
    pos : 85,
  },
  {
    name : "b-button F#0",
    nameText: "E",
    i : 23,
    pos : 145,
  },
  {
    name : "b-button G#0",
    nameText: "R",
    i : 24,
    pos : 175,
  },
  {
    name : "b-button A#0",
    nameText: "T",
    i : 25,
    pos : 205,
  },
  {
    name : "b-button C#1",
    nameText: "Y",
    i : 26,
    pos : 265,
  },
  {
    name : "b-button D#1",
    nameText: "U",
    i : 27,
    pos : 295,
  },
  {
    name : "b-button F#1",
    nameText: "I",
    i : 28,
    pos : 355,
  },
  {
    name : "b-button G#1",
    nameText: "O",
    i : 29,
    pos : 385,
  },
  {
    name : "b-button A#1",
    nameText: "P",
    i : 30,
    pos : 415,
  },
  {
    name : "b-button C#2",
    nameText: "Z",
    i : 31,
    pos : 475,
  },
  {
    name : "b-button D#2",
    nameText: "X",
    i : 32,
    pos : 505,
  },
  {
    name : "b-button F#2",
    nameText: "C",
    i : 33,
    pos : 565,
  },
  {
    name : "b-button G#2",
    nameText: "V",
    i : 34,
    pos : 595,
  },
  {
    name : "b-button A#2",
    nameText: "B",
    i : 35,
    pos : 625,
  },
];

const srcArr = [
  "sounds/C0.mp3",
  "sounds/D0.mp3",
  "sounds/E0.mp3",
  "sounds/F0.mp3",
  "sounds/G0.mp3",
  "sounds/A0.mp3",
  "sounds/B0.mp3",
  "sounds/C1.mp3",
  "sounds/D1.mp3",
  "sounds/E1.mp3",
  "sounds/F1.mp3",
  "sounds/G1.mp3",
  "sounds/A1.mp3",
  "sounds/B1.mp3",
  "sounds/C2.mp3",
  "sounds/D2.mp3",
  "sounds/E2.mp3",
  "sounds/F2.mp3",
  "sounds/G2.mp3",
  "sounds/A2.mp3",
  "sounds/B2.mp3",
  "sounds/CC0.mp3",
  "sounds/DD0.mp3",
  "sounds/FF0.mp3",
  "sounds/GG0.mp3",
  "sounds/AA0.mp3",
  "sounds/CC1.mp3",
  "sounds/DD1.mp3",
  "sounds/FF1.mp3",
  "sounds/GG1.mp3",
  "sounds/AA1.mp3",
  "sounds/CC2.mp3",
  "sounds/DD2.mp3",
  "sounds/FF2.mp3",
  "sounds/GG2.mp3",
  "sounds/AA2.mp3"
];